### PR TITLE
Grate 22.2

### PR DESCRIPTION
**Pull request by kwizart**
This is an attempt to rebase mesa grate branch to mesa 22.2.4

Warning displayed still not fixed:
```
grate_screen_get_shader_param: unsupported fragment-shader parameter: 28
grate_screen_get_shader_param: unsupported fragment-shader parameter: 25
```

Fixed warning but likely incorrect: (there is nothing drawn in glmark2)
See https://github.com/kwizart/mesa/commit/a9fffc052f46d1570b3cdabc5b9f4823bfdcbe01
```
[build] use-vbo=false:grate_draw_vbo() invalid index size: 0
../src/gallium/drivers/grate/grate_stream.c:165/grate_stream_begin(): Stream status isn't FREE
grate_stream_begin() failed: -1

```
There is also a SIGSEGV in glmark2 a little after.

### CODE REVIEW

**Comment by kwizart** [comment]
Also I think this patch is suspicious (but fixes a compilation issue with me)
https://github.com/kwizart/mesa/commit/de176a73848f1bc56c46aaf26fdfae4c9f49741c

**Comment by kwizart** [comment]
I've implemented PIPE_CAP_VIDEO_MEMORY
https://github.com/grate-driver/mesa/pull/17/commits/d0acb3c872ef654185fae6de9e2916e08dd014e7

It's likely inaccurate if assuming a grate kernel where gart(on Tegra20) or iommu is enabled...

**Comment by digetx** [comment]
Thank you! Applied to the new branch https://github.com/grate-driver/mesa/tree/22.2.4 Will test it after updating my Ubuntu install on A500. If any fixes will be needed, I'll add them on top of the new branch.

**Comment by kwizart** [comment]
Thanks.

Forgot to mention that I've dropped the commit that discard llvmpipe on neon
https://github.com/grate-driver/mesa/commit/389fff881b892e6acbd6ec8ade9baba63fe0968e

I've tried to report at llvm that has spotted an interesting regression without fixing the SIGILL
https://github.com/llvm/llvm-project/issues/59286
and reported to mesa upstream
https://gitlab.freedesktop.org/mesa/mesa/-/issues/7868

**Comment by digetx** [comment]
The grate glxgears work and llvmpipe is indeed still broken with neon, so I added back the workaround.

**Comment by digetx** [comment]
You may open grate-mesa issue for the neon bug status tracking. It may take some effort to figure out how to make llvm reproducer, I never touched llvm.

**Pull request closed without merging**
